### ISSUE TITLE
Proposal: add code to get tile indicies that overlap an arbitrary ROI

### ISSUE THREAD

**Issue by wronk** [geometalab/pyGeoTile#13]
Hi @Murthy10, I wrote some functionality that extends your package and wanted to get your take on whether I should include it here or publish as a separate package on pypi. 

For a recent project, I needed to get all the tiles indicies that belonged to a couple countries. To do that, I wrote some code to take an arbitrary boundary (specified as a geojson) and an arbitrary zoom level and then return a list of all tile inds at the specified zoom that overlap (at least partially) with that boundary. I wrote a depth-first search algorithm to accomplish this because it avoids having to store many tiles in memory. Pakistan, for example, has ~50 million zoom 18 tiles, but the maximum number of tiles ever stored in RAM was 39. 

It works by popping a tile off the last-in-first-out stack, zooming in one increment to get this tile's 4 sub-tiles, and checking if each of those also overlap with the boundary. If they do, they're put on the top of the stack and the cycle continues. The stack is initialized with the (whole-world) zoom 0 tile. Once a tile is found to both overlap with the boundary *and* be at the specified zoom (e.g., 18) its indicies are appended to the end of a text file and the tile is removed from the stack. There is also one enhancement where if a parent tile overlaps 100% with the boundary (i.e., it's completely contained), then the overlap computation is skipped for that tile and all its children. I found it took about 15 min to complete all of Pakistan at zoom 18 on a 2017 Macbook Pro.

I'm interested in what you think, but the obvious options to me seem like either:
1. Open a PR here. The main concern is that my function would add `shapely` as a dependency (but maybe there's a simple function I can write to calculate overlap between polygons).
2. Put this in a separate repo, and maybe you could link to it from your Readme/docs page as I think it's very relevant to `pygeotile`

**Comment by Murthy10** [comment]
Hi @wronk sounds like a cool tool and nice that you are using our pyGeoTile.
The purpose of pyGeoTile is to convert the different projections.
I think your tool is more advanced and a good practice example for pyGeoTile.
Hence it might be a better idea to put it in a repo on your own, but I really like to link it from this repo.

**Comment by wronk** [comment]
@Murthy10, sounds good, thanks. I'll post back here once it's ready (likely within a week or two).

**Comment by wronk** [comment]
@Murthy10, project is up here:
https://github.com/developmentseed/geodex

Would you mind adding a link? Also interested to hear if you have any feedback :)

**Comment by Murthy10** [comment]
I update the readme.md of pyGeoTile and mentioned your project as an example usage.
GeoDex looks like a cool and useful tool.  I'm looking forward to try it in action and will give you some feedback.
